---
- name: Update apt
  apt: update_cache=yes

# break up the packages and out of order to reduce install size and timeouts
- name: Install kali-linux-core
  apt:
    name: kali-linux-core
    state: latest

- name: Install kali-tools-web
  apt:
    name: kali-tools-web
    state: latest

- name: Install kali-tools-post-exploitation
  apt:
    name: kali-tools-post-exploitation
    state: latest

- name: Install kali-tools-reverse-engineering
  apt:
    name: kali-tools-reverse-engineering
    state: latest

- name: Install kali-tools-windows-resources
  apt:
    name: kali-tools-windows-resources
    state: latest

- name: Install kali metapackages
  vars:
    sys_packages:
      - kali-tools-reporting
      - kali-tools-crypto-stego
      - kali-tools-fuzzing
  apt: name={{ sys_packages }} state=latest

- name: Install kali-linux-default
  apt:
    name: kali-linux-default
    state: latest