- hosts: all
  gather_facts: True

  roles:
    - deb-common
    - kali-xrdp
    - kali-metapackages
    - kali-password
    - deb-vscode
    - deb-docker
    - deb-docker-images

  vars_files:
    - ../vars/vars.yml 