---
- name: Update apt
  apt: update_cache=yes

- name: upgrade a server
  apt: upgrade=full
  
- name: Install required system packages
  vars:
    sys_packages: [ 'python3-pip' ]
  apt: name={{ sys_packages }} state=latest

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
