---
#
# Tasks to be applied to some servers
#

# Add tasks for a specific role to this playbook...


- name: clone PowerUpSQL repository
  git:
    repo: https://github.com/NetSPI/PowerUpSQL.git
    version: master
    dest: /tools/PowerUpSQL
    clone: yes
    update: yes
    accept_hostkey: yes
