---
#
# Tasks to be applied to some servers
#

# Add tasks for a specific role to this playbook...


- name: clone privesc repository
  git:
    repo: https://github.com/enjoiz/Privesc.git
    version: master
    dest: /tools/privesc
    clone: yes
    update: yes
    accept_hostkey: yes
