---
#
# Tasks to be applied to some servers
#

# Add tasks for a specific role to this playbook...


- name: clone watson repository
  git:
    repo: https://github.com/rasta-mouse/Watson.git
    version: master
    dest: /tools/watson
    clone: yes
    update: yes
    accept_hostkey: yes
